# Generated by Django 6.1 on 2026-08-16 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_livesession_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='current_question_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='livesession',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz.question')),
            ],
            options={
                'ordering': ('submitted_at',),
                'constraints': [models.UniqueConstraint(fields=('participant', 'question'), name='unique_answer_per_participant_per_question')],
            },
        ),
    ]
