# Generated by Django 6.1 on 2026-08-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_livesession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='current_question_closed',
            field=models.BooleanField(default=False),
        ),
    ]
