# Generated by Django 6.1 on 2026-08-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='quiz_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='total_time_limit',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_kicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
