# Generated by Django 6.1 on 2026-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_aigenerationusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='bg_music_track',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
