# Generated by Django 6.1 on 2026-10-07 15:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_livesession_bg_music_track'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='game_pin',
            field=models.CharField(db_index=True, max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], db_index=True, default='WAITING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['live_session', 'is_kicked', 'is_admitted'], name='quiz_partic_live_se_810e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['live_session', 'score'], name='quiz_partic_live_se_91b95c_idx'),
        ),
    ]
